version: '3.8'
# docker files are configured for development only
services:
  db:
    image: postgres:15
    container_name: sewalk-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-pw
      POSTGRES_DB: sewalk
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sewalk"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    container_name: sewalk-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres-pw@db:5432/sewalk
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    container_name: sewalk-frontend
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  pgdata:
  frontend_node_modules:
