version: '3.8'

services:
  db:
    image: postgres:15
    container_name: jobfinder-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobfind
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: jobfinder-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/jobfinder
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: jobfinder-frontend
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: http://localhost:8000
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  pgdata:
