# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Make the start script executable
RUN chmod +x /app/start.sh

CMD ["/app/start.sh"]
#--reload is for development only, remove in production
